### ISSUE TITLE
Improve location handling -  do not break IEEE

### ISSUE THREAD

**Issue by MartinBrugnara** [CristianCantoro/latex_draft_example#2]
```latex  
\backgroundsetup{contents=\drafttext,
           color=draftwatermarkcolor,
           opacity=1,
           angle=90,
           position=current page.west,
           vshift=-10,
           scale=2
}
```

**Comment by CristianCantoro** [comment]
Thanks @MartinBrugnara, but this does not work for me, see the [output](https://i.imgur.com/M7VZEXg.png) below:
![Rendered PDF output](https://i.imgur.com/M7VZEXg.png "Rendered PDF output")

Can you try, please:
```latex
\backgroundsetup{contents=\drafttext,
         color=draftwatermarkcolor,
         opacity=1,
         angle=90,
         position=current page.west,
         vshift=-0.5\leftmargin,
         hshift=0.3\textheight,
         scale=2
}
```

**Comment by MartinBrugnara** [comment]
pff

-- Martin Brugnara

On Tue, May 8, 2018 at 12:25 PM, Cristian Consonni <notifications@github.com

**Comment by MartinBrugnara** [comment]
No, it breaks.

**Comment by CristianCantoro** [comment]
@MartinBrugnara, commit https://github.com/CristianCantoro/latex_draft_example/commit/f391be392ce7f62c8f5c089c8b8271c89dc3fbe2 introduces optional (named) arguments. So, it's not really a fix but you can use that to set the position of the draft text in the page as it suits your needs.

It would be great if you could test it.
